### ISSUE TITLE
Out of Stock not opening back to stock

### ISSUE THREAD

**Issue by trustedsec** [jamesgol/woocommerce-cart-stock-reducer#42] opened 2017-05-08 17:42 UTC
Here's an issue I'm running into with WooCommerce 3.0.5 with the latest development plugin.

We have tickets we sell, and want it to be held for 5 minutes before it times out. Lets use an example of 30 tickets. 

What will happen is the stock will run out and go to 0. When it goes to 0, as the tickets begin to expire, the tickets are replenished to the number on the products page to the number of individuals that didn't put payment information in. It never goes back to "In Stock", just remains out of stock with the quantity still being accurate.

<img width="116" alt="screen shot 2017-05-08 at 1 40 41 pm" src="https://cloud.githubusercontent.com/assets/3160808/25817003/fa305858-33f3-11e7-8487-4f0a5de88825.png">

Screenshot above. Thanks again for all of the assistance and for putting this together, it's really awesome!

**Comment by trustedsec** [comment] 2017-05-08 17:55
Some more details on this, looks like when you add to cart (when they are available) - it starts the counter, but then when you go to checkout, it says it's out of quantity. 

<img width="1149" alt="screen shot 2017-05-08 at 1 52 24 pm" src="https://cloud.githubusercontent.com/assets/3160808/25817626/e7fb2120-33f5-11e7-8d64-6943a8b38a22.png">

Here's the screenshot. When you go back, it shows a mixture of countdown and that it's not available:

<img width="1117" alt="screen shot 2017-05-08 at 1 53 03 pm" src="https://cloud.githubusercontent.com/assets/3160808/25817666/071957d4-33f6-11e7-88c8-73b62cbf13da.png">

**Comment by jamesgol** [comment] 2017-05-08 18:51
It definitely sounds like an issue, the WooCommerce 3.x changes made life more difficult, though in the long run it will be a good thing.

So I can get a setup to reproduce the issue.  Are these tickets 'Simple products' in WooCommerce?

**Comment by trustedsec** [comment] 2017-05-08 18:57
Yessir, simple products with the "virtual" content clicked. Thanks again!

**Comment by trustedsec** [comment] 2017-05-08 18:57
Screenshot below:

<img width="602" alt="screen shot 2017-05-08 at 2 56 52 pm" src="https://cloud.githubusercontent.com/assets/3160808/25820258/aacf1424-33fe-11e7-92d4-d8196420c855.png">

**Comment by trustedsec** [comment] 2017-05-08 18:58
Also note that this is using PayPal express checkout - not sure if that factors into anything.

**Comment by jamesgol** [comment] 2017-05-08 19:41
I tried a number of different slight variations and wasn't able to reproduce this at all.  Are you using any other WooCommerce plugins that affect stock/quantity or any form of caching?

**Comment by trustedsec** [comment] 2017-05-08 19:49
I'm using max quantity:

WooCommerce Max Quantity

**Comment by trustedsec** [comment] 2017-05-08 19:49
That's the only non standard one

**Comment by jamesgol** [comment] 2017-05-08 19:50
Can you disable that plugin and see if it that helps?  I don't have a copy of that plugin so I can't test against it

**Comment by trustedsec** [comment] 2017-05-08 20:02
Absolutely, driving right now but will test as soon as I'm home.

**Comment by trustedsec** [comment] 2017-05-08 22:48
After disabling that plugin, everything seems to be working now. Sorry for the post here and thanks for investigating. I did end up going with WooCommerce Min/Max Quantities plugin from WooCommerce and appear to be playing well with one another.

Thanks again for the help!

**Comment by jamesgol** [comment] 2017-05-08 22:52
If you send me a copy of that other plugin to james@gnuinter.net I can see if it's easy enough to make it play nicely together or at least make a note of the incompatibility.

**Comment by trustedsec** [comment] 2017-05-08 23:38
Hey @jamesgol - I spoke too soon. I disabled all of the plugins and tested with a larger population. Disabled all plugins and did the same thing. Same as before, doesn't get re-added after the time, stock shows Out of Stock (X). 

![18402259_10212997558592037_8082657754389198018_o](https://cloud.githubusercontent.com/assets/3160808/25829694/db1bee82-3425-11e7-874b-373034149e91.jpg)

**Comment by trustedsec** [comment] 2017-05-08 23:39
![screen shot 2017-05-08 at 7 38 49 pm](https://cloud.githubusercontent.com/assets/3160808/25829720/0e6ccf4a-3426-11e7-824a-3ca2c8b5cc6b.png)

**Comment by trustedsec** [comment] 2017-05-08 23:50
Here's basically what I'm doing:

1. Create a simple product - no special permissions or anything other than I specify a max quantity of 20. I also hit the virtual check box as well.

2. Have more than 20 interact with the site and try to purchase, some not. When I do that, it starts to get wonky, after time expirations, it gets added back but never shows it back in stock. Also some get the above picture sorry we do not have enough.

**Comment by jamesgol** [comment] 2017-05-08 23:52
Are you using any object caching on your site?  What other plugins/theme are you using?  

You are definitely using the latest version from GitHub?

**Comment by trustedsec** [comment] 2017-05-08 23:58
Pulled and installed via upload/add new zip here: https://github.com/jamesgol/woocommerce-cart-stock-reducer/archive/master.zip

Plugins:

WooCommerce 3.0.5
WooCommerce PayPal Express Checkout Gateway 1.2.1
reCAPTCHA for WooCommerce 1.0.3

That's it for plugins.

**Comment by jamesgol** [comment] 2017-05-09 00:26
I see the issue now and I'll have to spend some time to dig into it.  I've seen similar issues come up before.  What's happening is that as soon as the user gets kicked over to the payment plugin the order is placed but marked on hold.  I recall dealing with this a different way before, but it's yet another change that has to get dealt with for WooCommerce 3.x.

**Comment by jamesgol** [comment] 2017-05-09 00:54
I was thinking about this a bit more and I bet now that WC has changed some stuff around it might be easier to deal with this issue.
I suspect if you set 'Pending payment' under 'Ignore Order Status' this will solve your issue since it will keep the item from expiring out of the users cart, which could screw up the count.

**Comment by trustedsec** [comment] 2017-05-09 01:10
Awesome, let me give it a shot - thanks again man. I'll report back.

**Comment by trustedsec** [comment] 2017-05-09 01:16
Just confirming, this one right? Bottom select pending payments, then hit save. 

![screen shot 2017-05-08 at 9 15 30 pm](https://cloud.githubusercontent.com/assets/3160808/25831632/8800f4fa-3433-11e7-89b8-410ff4680745.png)

**Comment by jamesgol** [comment] 2017-05-09 01:19
Yup that's right.  When you get passed along to the payment processor WooCommerce keeps the items in the cart but also places an actual order with the status set to 'wc-pending'  (aka 'Pending payment').

**Comment by trustedsec** [comment] 2017-05-09 01:42
Still experiencing the same issue it looks like. After the time went out - still shows out of stock when testing, doesn't go back to in stock. Even though theres still 1 there. I think the count is right now, but I need to do some more testing there. 

![screen shot 2017-05-08 at 9 41 00 pm](https://cloud.githubusercontent.com/assets/3160808/25832194/28f026c6-3437-11e7-85f2-1513c20deaf9.png)

**Comment by jamesgol** [comment] 2017-05-09 01:45
I'd have to dig in more, but that should be the expected behavior.  Since an order has technically been placed and is in limbo waiting for payment.  Otherwise if we put that back in stock, WooCommerce will happily oversell the items because it's been kicked off out to PayPal. 

Really the best situation is to use some kind of payment processor that you handle completely on your site.

**Comment by trustedsec** [comment] 2017-05-09 01:51
What I did in this case was do 4 tickets. Added 3 - paid for them, on a separate browser, I added one ticket. Didn't go to the payment processor at all, just added to cart. When I purchased the 3, the quantity was correctly removed.

When I just added the 1, I waited 5 minutes for it to expire, after it expired, it shows 1 quantity, and it is never put back in stock. There was no direct checking out waiting for payment if that makes sense..

**Comment by jamesgol** [comment] 2017-05-09 02:58
I just tried to duplicate that result and could.  Here is exactly what I did:

1. Created new item with 4 in stock, set virtual, and price $35
2. On Browser 2, not logged into WP, added 3 to cart
3. On Browser 3, also not logged into WP, added 1 to cart.
4. On Browser 2 paid for items
5. On Browser 3, waited for item to time out.
6. After time out item shows in stock on browser as well as on WP Backend.

**Comment by trustedsec** [comment] 2017-05-09 13:59
Just tried it again (with a not logged in WP).

1. Create a new item with 4 in stock, and set to virtual.
2. Browser not signed into WP, added 3 to cart
3. 2nd Browser not signed into cart, added 1
4. Paid for 3 items
5. 2nd Browser refreshed page - got out of stock quantity - shows 0 on product page:

<img width="1214" alt="screen shot 2017-05-09 at 9 55 46 am" src="https://cloud.githubusercontent.com/assets/3160808/25854462/110fa466-349e-11e7-8377-afad37af9c76.png">

On inventory still shows 1:

<img width="929" alt="screen shot 2017-05-09 at 9 56 00 am" src="https://cloud.githubusercontent.com/assets/3160808/25854481/1f96b1e6-349e-11e7-8aed-ba684d6ad883.png">

On refreshed browser that had 1 checked out:

<img width="1162" alt="screen shot 2017-05-09 at 9 55 24 am" src="https://cloud.githubusercontent.com/assets/3160808/25854494/2af432fc-349e-11e7-8cb0-2b17b00c2550.png">

Browser where paid successfully for 3:

<img width="1130" alt="screen shot 2017-05-09 at 9 55 34 am" src="https://cloud.githubusercontent.com/assets/3160808/25854503/35e45dd6-349e-11e7-8a77-3fd8254c6fd8.png">

**Comment by trustedsec** [comment] 2017-05-09 14:07
Ensured there is no additional plugins or anything like that. I can reproduce this reliability going through the same steps.

**Comment by trustedsec** [comment] 2017-05-09 14:24
Thought maybe it was PayPal express checkout, I went in and disabled that and used the regular PayPal integration, same thing. 

<img width="1218" alt="screen shot 2017-05-09 at 10 24 29 am" src="https://cloud.githubusercontent.com/assets/3160808/25855631/ba6d6824-34a1-11e7-9286-32e362d12e18.png">

**Comment by trustedsec** [comment] 2017-05-09 14:33
Another interesting edge case.

1. 3 tickets.
2. Browser #1 - add 1 ticket
3. Browser #2 - add 2 tickets
4. Message below is presented, even though it is in my cart:

<img width="1220" alt="screen shot 2017-05-09 at 10 31 13 am" src="https://cloud.githubusercontent.com/assets/3160808/25856026/ccede720-34a2-11e7-93a1-19f80ba94fed.png">

Just a little confusing, since it technically is out of stock, but you've successfully added.

I'm testing different settings in WooCommerce right now to see if maybe the autoredirect had an issue. Just trying to bounce ideas to find the problem.

**Comment by jamesgol** [comment] 2017-05-09 14:34
Are you sure you don't have any object caching running on your site or any must-use plugins installed (maybe by your web-host?)

**Comment by jamesgol** [comment] 2017-05-09 14:37
Your latest test case is expected behavior.  There are 2 items in your cart and the message notifies you of that, if you want to add more items you have to wait until more might be available.

**Comment by trustedsec** [comment] 2017-05-09 14:43
Web host is a VPS, so I'm root on the box, No caching plugins or anything like that on the site. Disabled all plugins except for the WooCommerce one and this one.

**Comment by trustedsec** [comment] 2017-05-09 14:50
May have just figured it out. I'm going to do more testing, but looks like under inventory in WooCommerce if you enable stock management with a timer, they conflict with each other:

 
<img width="878" alt="screen shot 2017-05-09 at 10 46 25 am" src="https://cloud.githubusercontent.com/assets/3160808/25856889/534d705e-34a5-11e7-9afc-adfa9ae1431a.png">

**Comment by jamesgol** [comment] 2017-05-09 14:51
Can you try enabling the "Cash on delivery" payment method and using that?  That would help narrow the focus down to something related to post payment processing.

**Comment by trustedsec** [comment] 2017-05-09 14:53
NM. Still same issue going through the steps again.

**Comment by trustedsec** [comment] 2017-05-09 14:53
Sounds good, working on it now.

**Comment by jamesgol** [comment] 2017-05-09 14:54
All of my other WooCommerce settings are at the defaults, is there anything else you might have adjusted that I need to change to reproduce?

**Comment by trustedsec** [comment] 2017-05-09 14:56
Same issue with cash at hand. I'll go through, I was poking around settings at first, before landing on this plugin. Thanks again for all of the help. I'll go through settings and see if there is anything else. 

<img width="1152" alt="screen shot 2017-05-09 at 10 55 46 am" src="https://cloud.githubusercontent.com/assets/3160808/25857142/21599162-34a6-11e7-8b23-aaff21f636af.png">

**Comment by trustedsec** [comment] 2017-05-09 14:58
I am using guest checkout btw - not sure if that matters.

**Comment by trustedsec** [comment] 2017-05-09 15:04
Here's all of my settings - nothing unusual:

<img width="664" alt="screen shot 2017-05-09 at 10 57 25 am" src="https://cloud.githubusercontent.com/assets/3160808/25857478/37cf3d24-34a7-11e7-9b7d-5bf96450c758.png">

<img width="848" alt="screen shot 2017-05-09 at 10 57 46 am" src="https://cloud.githubusercontent.com/assets/3160808/25857484/3b953602-34a7-11e7-97e3-d98bcdfb4464.png">

<img width="1034" alt="screen shot 2017-05-09 at 11 02 43 am" src="https://cloud.githubusercontent.com/assets/3160808/25857489/3f2728fc-34a7-11e7-806a-a6d217d185f8.png">

<img width="1034" alt="screen shot 2017-05-09 at 11 03 21 am" src="https://cloud.githubusercontent.com/assets/3160808/25857505/49d0af26-34a7-11e7-83a3-5937f0eba9c2.png">

<img width="1146" alt="screen shot 2017-05-09 at 11 03 27 am" src="https://cloud.githubusercontent.com/assets/3160808/25857509/4d74e160-34a7-11e7-8e35-4a1c0e85172d.png">

<img width="809" alt="screen shot 2017-05-09 at 11 03 37 am" src="https://cloud.githubusercontent.com/assets/3160808/25857511/50663d56-34a7-11e7-823e-03969a574fa3.png">

**Comment by trustedsec** [comment] 2017-05-09 15:05
Only two plugins enabled:

<img width="771" alt="screen shot 2017-05-09 at 11 05 16 am" src="https://cloud.githubusercontent.com/assets/3160808/25857542/69b5027e-34a7-11e7-8e28-d567c9c61690.png">

**Comment by jamesgol** [comment] 2017-05-09 15:21
It more than likely doesn't have anything to do with it, but what theme are you using?

**Comment by trustedsec** [comment] 2017-05-09 15:40
Refer:

https://wordpress.org/themes/refur/

**Comment by trustedsec** [comment] 2017-05-09 16:11
May have found something here. Saw this in the Apache error log:

[Tue May 09 14:22:56.496811 2017] [:error] [pid 24885] [client IPADDRESS:55043] post_status was called incorrectly. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->validate_checkout, WC_Checkout->check_cart_items, do_action('woocommerce_check_cart_items'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, WC_Cart_Stock_Reducer->check_cart_items, WC_Cart_Stock_Reducer->expire_items, WC_Cart_Stock_Reducer->is_expired, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong. This message was added in version 3.0., referer: https://www.website.com/checkout/

**Comment by jamesgol** [comment] 2017-05-09 16:13
I just tried that theme and still can't reproduce the issue with the theme.  If you update to the latest dev build you'll get rid of that notice, I saw it last night too when I had debugging enabled.  It shouldn't cause any issues, it's just a deprecated notice because WooCommerce 3.x majorly changed stuff around, still backwards compatible though

**Comment by trustedsec** [comment] 2017-05-09 16:20
Yeah, pulled the latest. Didn't seem to have an impact unfortunately, still same thing. At a loss here. 

There a way to purge all of the WooCommerce data and start from scratch and try that (i.e. settings in database, etc.).

**Comment by trustedsec** [comment] 2017-05-09 16:21
Found it. Gonna try to purge everything woocommerce first.

**Comment by jamesgol** [comment] 2017-05-09 16:24
I might be on to something, give me a bit and I'll see.

**Comment by trustedsec** [comment] 2017-05-09 16:31
Okay, thanks!

**Comment by trustedsec** [comment] 2017-05-09 16:37
Know you are working on something, just wanted to give context to testing a fresh install:

I completely nuked everything including purging the via define( 'WC_REMOVE_ALL_DATA', true); and deactivated/deleted. Reinstalled WooCommerce, put me through the wizard to create the pages/carts, etc. for a fresh install, nothing new and kept settings the same. 

Installed the latest of cart-stock-reducer.

1. Added new simple product, virtual, 3 quantity
2. Browser 1 - add to card (just 1)
3. Browser 2 - add 2 to cart
4. Do cash payment via browser 2
5. Refresh Browser 1 page:

<img width="1168" alt="screen shot 2017-05-09 at 12 36 39 pm" src="https://cloud.githubusercontent.com/assets/3160808/25861909/32d217bc-34b4-11e7-82f7-24c909ee4c38.png">

**Comment by trustedsec** [comment] 2017-05-09 16:52
Some more on this, when I get the message above, if I actually remove it from the cart:

<img width="1108" alt="screen shot 2017-05-09 at 12 51 20 pm" src="https://cloud.githubusercontent.com/assets/3160808/25862499/473e1b04-34b6-11e7-9cad-200dc046378c.png">

You can see it under inventory get added as expected, but still shows out of stock:

<img width="87" alt="screen shot 2017-05-09 at 12 51 35 pm" src="https://cloud.githubusercontent.com/assets/3160808/25862513/512df742-34b6-11e7-85c3-bdf538597c06.png">

**Comment by trustedsec** [comment] 2017-05-09 17:36
Adding another test case:

1. Max quantity 3
1. Browser 1 - add to card 1 item
2. Browser 2 - add 1 item to cart, and checkout/pay
3. Refresh Browser 1 - still OK
4. Go back to Browser 2 - purchase another item
5. Refresh Browser 1 - error message that out of stock

**Comment by jamesgol** [comment] 2017-05-09 17:37
Can you test out the latest development version, should be fixed.

**Comment by trustedsec** [comment] 2017-05-09 17:38
You rock man. Grabbing now and testing.

**Comment by jamesgol** [comment] 2017-05-09 17:39
Actually one second, I pushed it into the wrong place on git.  Had detached head

**Comment by trustedsec** [comment] 2017-05-09 17:39
No prob.

**Comment by jamesgol** [comment] 2017-05-09 17:46
Ok give it a try now.

**Comment by trustedsec** [comment] 2017-05-09 17:47
Giving it a shot

**Comment by trustedsec** [comment] 2017-05-09 17:52
We are definitely closer and almost there. There is still a little bit of a bug I think. I'm going to go through it again just to test but here is whats happening:

1. 3 quantity, virtual, etc as last time.
2. Browser 1 - add 1 item
3. Browser 2 - add 2 items
4. Checkout and pay for ticket on browser 2
5. Go back to Browser 1 and hit refresh

When you hit refresh, the timer is now gone:

<img width="1211" alt="screen shot 2017-05-09 at 1 49 40 pm" src="https://cloud.githubusercontent.com/assets/3160808/25864773/a373c4ca-34be-11e7-8075-d2b145896d7b.png">

I can still go through and proceed to checkout and process the payment, but it isn't displaying the actual timer of how long left I have to go.

The quantity and the out of stock match perfectly. That's the only issue I see. 

Nice work on this!!

**Comment by jamesgol** [comment] 2017-05-09 17:58
The timer not showing up might be related to the other issue that was holding me back from releasing the next version, was getting a javascript error in the browsers console due to something not being ready at the time.  Hadn't dug into that one yet, but check your browser console for any errors related to that

**Comment by trustedsec** [comment] 2017-05-09 18:04
No specific console errors. I don't think the timer is actually working at this point. I've had my browser open for about 10 minutes now and it still hasn't removed it from the cart.

<img width="1413" alt="screen shot 2017-05-09 at 2 02 28 pm" src="https://cloud.githubusercontent.com/assets/3160808/25865260/5a2c215c-34c0-11e7-97cb-01633bf05873.png">

**Comment by trustedsec** [comment] 2017-05-09 18:05
OK, I'm an idiot. Might be on my end. When I enabled the new plugin, the settings got nuked and had to go back into integration. Let me check again.

**Comment by trustedsec** [comment] 2017-05-09 18:08
Awesome man. It's fixed! Thank you for all of the help and for putting this together. Really the only thing out there that does this.

Do you have a donation page or anything I can do to help contribute for your time?

**Comment by trustedsec** [comment] 2017-05-09 18:09
Just saw the link to donate. Thanks again - just did. Appreciate all of the help.

**Comment by jamesgol** [comment] 2017-05-09 18:09
There is a donation button on https://wordpress.org/plugins/woocommerce-cart-stock-reducer/

I'm going to push out an official updated version that has these changes a bit later today.

**Comment by jamesgol** [comment] 2017-05-09 18:09
Cheers, Thanks!

**Closed as completed** 2017-05-10 20:21 UTC
