### ISSUE TITLE
WooCommerce 2.6.14 memory exhaustion 

### ISSUE THREAD

**Issue by reyo** [jamesgol/woocommerce-cart-stock-reducer#36] opened 2017-03-20 22:54 UTC
Hi!

Plugin uses all memory and / or meets the PHP script exec time.

Commenting out that line from main include fixes the problem.

Line 74:
`add_action( 'init', array( $this, 'load_plugin_textdomain' ) );`

WPML is used.

**Comment by jamesgol** [comment] 2017-03-23 14:25
I've not experienced this yet and don't see any reason it should, but I'll do some further digging to see if I can reproduce it.

I suspect it would be related to your WPML setup, can you get me a more complete description of how it is setup?

**Comment by jamesgol** [comment] 2017-03-23 16:25
I tried to reproduce this with a basic setup and had no luck.  I'm going to need more information to be able to replicate your scenario.

**Comment by xpafiolis** [comment] 2017-04-11 18:00
Hi Jamesgol, Love the plugin, running it on a large site moving tons of inventory. 

I also have just had to disable the plugin as of this morning, had a sale and it took down the site. php queries bogging down apparently coming from the plugin. Engineers said a ton of slow queries bogged it down. 

To get the site back up and running i upgraded to WC 3.01 and all plugins. in the end stock reducer had to be disabled and everything running fine now

not sure what info helps you but would love to get it up and running again.

**Comment by jamesgol** [comment] 2017-04-11 18:11
@xpafiolis Are you using WPML?  If not, please open up another issue since I'd like to keep this for @reyo to provide info that is likely related to WPML.

I haven't tested the code on a large site, honestly I don't even use the plugin myself I just built it for fun one weekend. What do you define as a large site?  How many products, orders, active sessions, etc. If you have a way to easily export everything I could try to duplicate the same setup locally and see where it can be optimized. Was everything fine with 2.6.x and only was excessive with 3.x?  I have not finished completely supporting 3.x yet, WooCommerce has changed enough around that is much better in the long run but makes it difficult in the short term.

**Closed as completed** 2017-05-11 17:03 UTC
